### ISSUE TITLE
Lambda Authorization failed

### ISSUE THREAD

**Issue by adelpuva** [aws/aws-sdk-android#166] opened 2016-07-05 10:40 UTC
Hi!

I log user with this code:
```
Map<String, String> logins = provider.getLogins();
if (logins == null) {
    logins = new HashMap<>();
 }
logins.put(providerName, token);
provider.setLogins(logins);
```
where _providerName_ is my Cognito User Pool Provider while _token_ is the JWTToken.

And create a lambda factory with this code:
```
ClientConfiguration config = new ClientConfiguration();
config.setSocketTimeout(5 * 60 * 1000);
lambdaFactory =  new LambdaInvokerFactory(context, regions, provider, config);
```
After provider session credential expired I can not call lambda any more, also if I call _provider.getCredentials()_ (after this call session credential seems refreshed, infact _provider.getSessionCredentitalsExpiration()_ return a new date)

Lambda always trows an error that says "_is not authorized to perform ..._"

What is the right way to avoid this error? I'm missing same process code? I can't ask the user to make login every hour! :(

Thank you.

P.S.
I'm using last sdk: 2.2.20

**Comment by jbailey2010** [comment] 2016-07-18 23:05
Hi,

I suspect what's happening is your credentials provider is losing the login it had on the initial call, so when you do a refresh it's getting credentials for an unauth id. This could be confirmed by checking that the auth role has lambda access but unauth does not. If so, give the flow your credentials provider is following another look. It should be a singleton whenever possible.

Thanks,
Jeff

**Comment by adelpuva** [comment] 2016-07-27 08:00
I resolved (at this moment) checking provider session expiration every where I must use **lambda**, and call _userPool.getCurrentUser().getSessionInBackground()_ saving user credential (but I'm not like it!) because sometimes _getAuthenticationDetails()_ is called.

Yes, my provider is a private static attributes, It's created one time.

**Comment by mreddyg** [comment] 2016-08-03 17:51
When userPool.getCurrentUser().getSessionInBackground() in called, the SDK first checks for valid cached tokens. If there are no valid cached tokens, it tries to use cached refresh token to get a new set of tokens. getAuthenticationDetails() is called when the refresh token has also expire, and hence the user credentials (Username + password) are required to authenticate before vending new tokens.
A bug in the Android SDK caused getAuthenticationDetails() to be invoked even after a successful token refresh. This bug has been fixed in Android SDK ver 2.2.21.
So using  "Cognito User Pool Provider" as  a credentials provider with Cognito Identity should work as intended.

**Comment by adelpuva** [comment] 2016-08-18 10:06
Thank you @mreddyg,  I'm using 2.2.22 version

**Comment by wdane** [comment] 2016-09-08 21:47
Assuming resolved, please feel free to re-open if more problems occurs or if this is not resolved.

**Closed by wdane** 2016-09-08 21:47 UTC
Labels: question
