### ISSUE TITLE
Unable to upload files to S3

### ISSUE THREAD

**Issue by gutierrezayuso** [aws/aws-sdk-android#95] opened 2016-02-10 16:11 UTC
When I try to upload files (>1MB) to S3 the upload process never ends, and in some cases it throws an exception like these:

```
AmazonHttpClient: Unable to execute HTTP request: Write error: ssl=0xb7e83110: I/O error during system call, Broken pipe
javax.net.ssl.SSLException: Write error: ssl=0xb7e83110: I/O error during system call, Broken pipe
   at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
   at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:765)
   at com.android.okio.Okio$1.write(Okio.java:70)
   at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
   at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
   at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:291)
   at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
   at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
   at com.amazonaws.http.UrlHttpClient.write(UrlHttpClient.java:172)
   at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:129)
   at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
   at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
   at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4212)
   at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1619)
   at com.crossbowandhills.emotions.api.aws.AmazonWebServices$2.run(AmazonWebServices.java:89)
```

```
AmazonHttpClient: Unable to execute HTTP request: Read timed out
java.net.SocketTimeoutException: Read timed out
   at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
   at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
   at com.android.okio.Okio$2.read(Okio.java:113)
   at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:147)
   at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:94)
   at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
   at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
   at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:496)
   at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
   at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:25)
   at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72)
   at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66)
   at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
   at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4212)
   at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1619)
   at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:194)
   at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:76)
   at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:41)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:818)
```

I've downloaded the S3TransferUtilitySample and I have exactly the same problem uploading files.

But if I try to upload smaller files (50-60KB) the upload process finishes without trouble.

I'm using aws-sdk version 2.2.11 on a Nexus 4 with Android 5.1.1 without any firewall. And the S3 bucket is in the eu-west-1 region.

**Comment by wdane** [comment] 2016-02-11 20:19
Closing as this is a duplicate of https://github.com/aws/aws-sdk-android/issues/94. I've added your details to that issue.

**Comment by fosterzhang** [comment] 2016-02-19 22:10
@gutierrezayuso You posted two exceptions here. The first one is usually caused by unstable network, say switching between Wifi and cellular, or frequently reconnects. The SSL connection is broken as a result. The only recommendation is to find a getter network. The second one is caused by slow network. Try to increase socket timeout via [ClientConfiguration.setSocketTimeout(int)](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setSocketTimeout(int)). Hope it will help.

**Comment by fosterzhang** [comment] 2016-02-26 20:37
Closing this as it's not an SDK issue. Feel free to reopen it if the same issue occurs.

**Closed** 2016-03-01 04:54 UTC
Labels: question
