### ISSUE TITLE
User Pools - Sign in failed

### ISSUE THREAD

**Issue by adelpuva** [aws/aws-sdk-android#132] opened 2016-05-11 13:40 UTC
Hi,
I'm using last SDK version (2.2.16) and I noticed a problem with th SignIn. 

With my code (and also the sample code: https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoYourUserPoolsDemo) I cannot sign in, the exception is this:

_05-11 02:02:44.296 4774-4774/com.amazonaws.youruserpools.CognitoYourUserPoolsDemo E/App Error: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Incorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: cdb193d0-1778-11e6-983f-1911089a757c)_

I try to delete user from User Pools to see the feedback and the exception is:

_05-11 02:07:22.798 4774-4774/com.amazonaws.youruserpools.CognitoYourUserPoolsDemo E/App Error: com.amazonaws.services.cognitoidentityprovider.model.ResourceNotFoundException: Username/client id combination not found. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 73cd3a27-1779-11e6-b690-e9ea51410dcd)_

I try to change password, the procedure works fine, but the _SignIn_ no: the same exception of above.

Thank you

**Comment by chetanme** [comment] 2016-05-11 21:00
I investigated the request ids you posted and the 1st one at 02:07 failed due to invalid password. Are you sure you entered the right password there? Are you doing this from an emulator? Can you try this from a different device to rule out any device specif issues?

The second request id failed because you were trying to authenticate a user which didn't exist. I think it is expected since you say that you deleted the user.

**Comment by adelpuva** [comment] 2016-05-12 07:58
Yes, I write a simple code where I put username and password by code (no by form - EditText - ).

When I call _signUpInBackground_ and receive confirm code from email I call _getSessionInBackground_ method. Inside _AuthenticationHandler_ callback use this code with the username passed by method (It's the same I used to register) and password written in the code :

> AuthenticationDetails authenticationDetails = new AuthenticationDetails(userId, password, null);
> authenticationContinuation.setAuthenticationDetails(authenticationDetails); authenticationContinuation.continueTask();

But the sign in failed always :(

I not used emulator, but two different device, and I test also your sample code....

Test with my code:
**Samsun GT-I93000** / Android **4.3**
-  Request ID: 7a599d5e-1812-11e6-983f-1911089a757c
-  username: test
-  password: Test0001

**LGE - Nexus 5** / Android **6.0.1**
- Request ID: 0fe38407-1814-11e6-a112-cf41276dfd85
- Username: test1
- Password: Test0001

Test with your sample code:
**LGE - Nexus 5** / Android **6.0.1**
- Request ID: 5b23c7aa-1815-11e6-82b6-c70e23c9284f
- Username: test2
- Password: Test0001

**Samsun GT-I93000** / Android **4.3**
-  Request ID: 0ebde870-1817-11e6-b9a3-f964f7946b63
-  username: test3
-  password: Test0001

Thank you

**Comment by chetanme** [comment] 2016-05-12 14:42
Ok. You are not confirming the new signed up user before trying to authenticate. You should call the [confirmSignUp](http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-android-sdk.html#using-amazon-cognito-user-identity-pools-android-sdk-confirm-user-registration) method with the code you received and once that call succeeds call the sign in method.

All the users created are unconfirmed by default and they are not allowed to sign in. The flow then becomes SignUp > Confirm > SignIn. If you do not want the confirmation step, you can auto confirm users using our [PreSignUp trigger](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#aws-lambda-triggers-pre-registration-example) hook and returning the service "autoConfirm=true" from this lambda function. The service will create confirmed users in that case.

**Comment by adelpuva** [comment] 2016-05-12 15:17
Sorry, Perhaps I did not explain well :(

...my complete process is:

> signUpInBackground -> onSuccess -> confirmSignUpInBackground -> onSuccess -> getSessionInBackground

But no works! 

And I as write above, I compiled the sample (from here https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoYourUserPoolsDemo) and It does not work either. I cannot SignIn!

Maybe is a misconfiguration of my User Pools / Identity Pools?

**Comment by chetanme** [comment] 2016-05-13 07:16
Apologies but can you post a request id for failed authentication with its time stamp? I would like to investigate this further in our logs.

I also want to mention that currently our SDKs have [this bug](https://forums.aws.amazon.com/thread.jspa?threadID=230694). So if you are trying this on devices which have language settings other than English, sign in will fail. The fix for this will be rolled our with out next SDK release.

**Comment by adelpuva** [comment] 2016-05-13 07:24
Well! I changed device language to English and SignIn works! I'm waiting for the next release.... I hope soon :)

**Closed** 2016-05-13 07:26 UTC
Labels: question

**Comment by danielesegato** [comment] 2016-05-13 12:28
@chetanme why is the issue been closed? the problem has not been solved yet

**Comment by chetanme** [comment] 2016-05-13 16:00
We are tracking it [here](https://github.com/aws/aws-sdk-ios/issues/377). Bot iOS and Android have the same issue and will be resolved together.

**Comment by guipingzhang** [comment] 2016-06-03 03:25
I hope I would find this issue 2 days ago. It seems to work in my mobile as I change the device language as English. In China,the device language is usually set as Chinese. I strongly suggest you can solve this problem, as we cannot ask app users to set their device language as English. Thank you very much!

**Comment by chetanme** [comment] 2016-06-03 04:24
As we posted on the tracking issue, this has been resolved already. It was resolved with [2.2.17](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md) Android SDK.

**Comment by Luzgan** [comment] 2016-08-03 15:16
Hi,

I wanted to reopen this task again - simply because it seems that I have the very same problem with SDK. But most importantly - I have Android SDK 2.3.0.

When it comes to the flow, I have exactly the same as @adelpuva. So, Signing up working without an issue, confirming sing up working without an issue and then when I try to sign in I am getting "Incorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: e108adc9-598a-11e6-8e54-61aadf840d02)".

Is it possible, that bug that you had before 2.2.17 was reintroduced in 2.3.0?

**Comment by Luzgan** [comment] 2016-08-03 15:59
Also wanted to note, that this time it seems to be not related with language, since emulator language is set to English US.

**Comment by guipingzhang** [comment] 2016-08-04 07:03
@Luzgan 

In early June, I set the length of password as 6 and could register a new user in User pool (SDK 2.2.17), but couldn't login with the user. Then I followed the default policy ( minimum length of password is 8 and with number, uppercase letters, lowercase letters and special character).  
Your can read this, https://github.com/aws/aws-sdk-android/issues/146#issuecomment-224363511

**Comment by Luzgan** [comment] 2016-08-04 07:12
@guipingzhang 

In my case I am following default policy as well, so unfortunately I don't think its related.

**Comment by uncleleonfan** [comment] 2016-12-01 11:29
@Luzgan @guipingzhang @adelpuva @chetanme @danielesegato @ I also meet this problem when I sign up, I'm using SDK 2.3.3,  anyway to save my life? thanks!

**Comment by uncleleonfan** [comment] 2016-12-02 02:49
Update, I delete my user pool and create a new one, problem go away, strange enough. Anyway, I save myself, thank god.

**Comment by AnandhiRaghuraman** [comment] 2019-01-30 07:05
I am user aws_java-sdk 1.11.360, I am able to sign up but sign in fails with this exception
Incorrect username or password. My Request Id is ID: 2be0b181-2450-11e9-a15b-3d35ecadad5f
I am using temporary password coded in my properties file to sign in and was receiving a challenge FORCE_CHANGE_PASSWORD, to which i responded with a new password. 
The code was working fine for 3 users and stopped working and started to throw above exception.
Now i deleted that user pool, identity pool and created new. But still not working

**Comment by taouichaimaa** [comment] 2021-11-24 12:18
Hi i'm having the same issue. the users exist in the userpool,they're all confirmed upon signup but it signin fails . Code reset and signup work just fine.
