### ISSUE TITLE
andriod aws cleanTransferListener not working

### ISSUE THREAD

**Issue by jitendraramoliya** [aws/aws-sdk-android#73] opened 2015-10-28 06:45 UTC
andriod aws cleanTransferListener not working in my app. I am using S3Transfer Utility to transfer data from local to server. I am using Wifi Data and my Sdk version is 2.2.7.

    I have set observer.setTransferListener(new UploadListener()); Listener while uploading my Image and video file on amazon s3 server. But when I am trying to clear Listener , It wouldn't be clear Listener. 

Why I am getting this problem. Any Provide me solution on this issue ASAP

**Comment by wdane** [comment] 2015-10-29 22:40
I cannot reproduce this issue.  I just tried uploading a 4 and 25 MB file using the following TransferListener

       transferObserver.setTransferListener(new TransferListener() {
            @Override
            public void onError(int arg0, Exception arg1) {
                Log.e(TAG, "Error", arg1);
            }
            @Override
            public void onProgressChanged(int arg0, long arg1, long arg2) {
                Log.d(TAG, "id: " + arg0 + " Transferred " + arg1 + "/" + arg2);
                if (arg1 > arg2 / 4) {
                    to.cleanTransferListener();
                    unregister = true;
                }
            }
            @Override
            public void onStateChanged(int arg0, TransferState arg1) {
                Log.d(TAG, "Stated changed to " + arg1);
            }
        });

and I saw logs for 1/4 of the upload as expected and then verified the upload completed successfully.

Is this happening on all devices you are testing (What OS's are you testing on?)?  Is this consistent or intermittent?  Does this also happen over non-wifi like 3G?

**Comment by fosterzhang** [comment] 2015-11-24 19:18
Closing this as we can't reproduce the problem.

**Closed** 2015-11-24 19:20 UTC
