### ISSUE TITLE
TransferListener not firing periodically and not showing progress

### ISSUE THREAD

**Issue by jitendraramoliya** [aws/aws-sdk-android#92] opened 2016-02-01 11:31 UTC
I am using this code for upload video file. Video file is uploaded successfully but not getting progress periodically. its only one time show 0% progress. after then uploading video and getting **"GC_FOR_ALLOC freed 1191K, 20% free 7353K/9108K, paused 4ms, total 4ms"** message in log but not getting progress1 log and even not firing any method from transferlistener

TransferUtility transferUtilitys = new TransferUtility(sS3Client,
                    MainActivity.this);

            TransferObserver observer1 = transferUtilitys.upload(Constants.BUCKET_NAME, "test" + "/" + file.getName(),
                    file, objectMetadata);

            observer1.setTransferListener(new TransferListener() {

                @Override
                public void onError(int id, Exception e) {
                    Log.e(TAG, "Error during upload: " + id, e);
                    Toast.makeText(MainActivity.this, "Error during upload: " + id, Toast.LENGTH_SHORT).show();

                }

                @Override
                public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {

                    int progress = (int) ((double) bytesCurrent * 100 / bytesTotal);
                    Log.e("", "progress1::" + progress);

                }

                @Override
                public void onStateChanged(int id, TransferState newState) {
                    Log.e("", "state1::" + newState);
                }
            });

**Comment by fosterzhang** [comment] 2016-02-01 19:05
Unable to reproduce. Closing this and in favor of the same issue reported in the sample repo [#43](https://github.com/awslabs/aws-sdk-android-samples/issues/43).

**Closed** 2016-02-01 19:19 UTC
