### ISSUE TITLE
IllegalStateException: Cannot perform this operation because the connection pool has been closed.

### ISSUE THREAD

**Issue by ushastikin** [aws/aws-sdk-android#305] opened 2017-06-08 09:00 UTC
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
S3 Android Mobile SDK

* In what version of SDK are you facing the problem?
2.4.3 and 2.4.4

* Is the issue limited to Simulators / Actual Devices?
Actual Devices

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
The crash appears on Android 6.0.1

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
I have not been able to reproduce this issue. I'm only receiving crash reports from production builds. The uploads can be done with a cellular data and with WiFi, so I am not sure about the status.

* Please include a stacktrace if applicable.
2.4.4 vesrion (please see also an attached stacktrace file from Fabric - [io.ibuddy.android.ibuddy_issue_31_crash_593858A701D40001629FC48F125CF97A_9d9d436f4c0b11e7aff456847afe9799_0_v2.txt](https://github.com/aws/aws-sdk-android/files/1060435/io.ibuddy.android.ibuddy_issue_31_crash_593858A701D40001629FC48F125CF97A_9d9d436f4c0b11e7aff456847afe9799_0_v2.txt)):

> Fatal Exception: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
>        at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1036)
>        at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:666)
>        at 
android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:399)
>        at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:905)
>        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
>        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
>        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
>        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
>        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
>        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
>        at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.getTransferById(SourceFile:804)
>        at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.execCommand(SourceFile:300)
>        at com.amazonaws.mobileconnectors.s3.transferutility.TransferService$UpdateHandler.handleMessage(SourceFile:240)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:148)
>        at android.os.HandlerThread.run(HandlerThread.java:61)

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by afvilalva** [comment] 2017-06-27 14:05
Facing same problem as @ushastikin in a very similar cenario.

- What service are you using?
S3 Android Mobile SDK

- In what version of SDK are you facing the problem?
aws-android-sdk-core:2.4.3
aws-android-sdk-s3:2.4.3

- Is the issue limited to Simulators / Actual Devices?
Actual Devices

- Can your problem be resolved if you bump to a higher version of SDK?
No

- Is this problem related to specific Android/OS version?
Problem already seen in Lollipop and Marshmallow devices

- Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Unfortunately we weren't able to reproduce the problem in office and **for now** we only saw this issue while in mobile networks

**Stacktrace**

> 06-26 06:00:06.149 D/RemoteStorage( 2806): Uploading image: 20170626-090001916.jpg
06-26 06:00:06.159 W/System.err( 2806): java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
06-26 06:00:06.161 W/System.err( 2806): 	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:982)
06-26 06:00:06.162 W/System.err( 2806): 	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:600)
06-26 06:00:06.162 W/System.err( 2806): 	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:349)
06-26 06:00:06.162 W/System.err( 2806): 	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:1032)
06-26 06:00:06.162 W/System.err( 2806): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:972)
06-26 06:00:06.162 W/System.err( 2806): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
06-26 06:00:06.162 W/System.err( 2806): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
06-26 06:00:06.162 W/System.err( 2806): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
06-26 06:00:06.162 W/System.err( 2806): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
06-26 06:00:06.162 W/System.err( 2806): 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
06-26 06:00:06.162 W/System.err( 2806): 	at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.getTransferById(TransferDBUtil.java:737)
06-26 06:00:06.162 W/System.err( 2806): 	at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.execCommand(TransferService.java:288)
06-26 06:00:06.162 W/System.err( 2806): 	at com.amazonaws.mobileconnectors.s3.transferutility.TransferService$UpdateHandler.handleMessage(TransferService.java:228)
06-26 06:00:06.162 W/System.err( 2806): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-26 06:00:06.162 W/System.err( 2806): 	at android.os.Looper.loop(Looper.java:135)
06-26 06:00:06.162 W/System.err( 2806): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by kvasukib** [comment] 2017-06-27 18:49
Thanks @ushastikin and @afvilalva for reporting to us. We are looking into it.

**Comment by afvilalva** [comment] 2017-08-31 13:02
Hi guys,
I noticed something that may be useful. Yesterday, there were two devices in the same network and they crashed at the same time. 
It rang me a bell if the issue isn't in a server answer's exception or a specific network condition which closes the DB.

**Comment by yshubin** [comment] 2017-10-02 11:35
Caught it too on 2 devices.

What service are you using?
S3 Android Mobile SDK

In what version of SDK are you facing the problem?
com.amazonaws:aws-android-sdk-core:2.4.2
com.amazonaws:aws-android-sdk-s3:2.4.2

Is the issue limited to Simulators / Actual Devices?
Actual Devices

Is this problem related to specific Android/OS version?
Samsung SM-G935F Android 7.0
LGE VS835 Android 7.0

Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Unfortunately we weren't able to reproduce the problem in office and saw this in our crash tracker

Stacktrace:
`java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:982)
	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:600)
	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:349)
	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:1032)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:972)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
	at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.getTransferById(TransferDBUtil.java:708)
	at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.execCommand(TransferService.java:288)
	at com.amazonaws.mobileconnectors.s3.transferutility.TransferService$UpdateHandler.handleMessage(TransferService.java:228)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by afvilalva** [comment] 2017-10-16 19:26
Question.
Can I remove this call from "TransferService.onDestroy()" ?
`dbUtil.closeDB();`

**Comment by afvilalva** [comment] 2017-10-23 15:19
Hi all,
I'm trying to give my contribution but I'm focused more on symptomatics effects since It's hard to debug without reproduce it in laboratory.
It seens the problem happens when the OS need resources and kills TransferService, closing TransferDBUtil instance (which is a singleton), so any other access to database will cause the reported crash.
I builded a modified library version for test purposes and haven't seen the crash happening since then (have already pass 5 days).

Please, can anyone else facing it help me confirm this change can fix the problem? diff below

Note: Please ignore the "START_STICKY" modify. It's for another issue
```
$ git diff
diff --git a/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferService.java b/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferService.java
index baaf2a21..7c9011db 100644
--- a/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferService.java
+++ b/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferService.java
@@ -131,7 +131,7 @@ public class TransferService extends Service {
     public void onCreate() {
         super.onCreate();

-        LOGGER.debug("Starting Transfer Service");
+        LOGGER.debug("Starting Transfer Service (Stick)");
         dbUtil = new TransferDBUtil(getApplicationContext());
         updater = new TransferStatusUpdater(dbUtil);

@@ -203,8 +203,9 @@ public class TransferService extends Service {
         }
         /*
          * The service will not restart if it's killed by system.
+         * afvilalva: Changing to START_STICK. We need this service running, no matter what
          */
-        return START_NOT_STICKY;
+        return START_STICKY;
     }

     @Override
@@ -221,7 +222,7 @@ public class TransferService extends Service {
         handlerThread.quit();
         TransferThreadPool.closeThreadPool();
         S3ClientReference.clear();
-        dbUtil.closeDB();
+//        dbUtil.closeDB();
         super.onDestroy();
     }
```

**Comment by totalityorbust** [comment] 2018-02-05 19:55
What service are you using?
S3 Android Mobile SDK

In what version of SDK are you facing the problem?
2.4.7

Is the issue limited to Simulators / Actual Devices?
Actual Devices

Can your problem be resolved if you bump to a higher version of SDK?
No

Is this problem related to specific Android/OS version?
The crash appeared on versions of Android 5, 6 and 7

Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
There doesn't seem to be a predictable way to replicate the issue. 

Please include a stacktrace if applicable.

java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
                                                                       at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
                                                                       at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
                                                                       at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
                                                                       at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
                                                                       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
                                                                       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                                       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
                                                                       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                                                                       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
                                                                       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
                                                                       at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.getTransferById(TransferDBUtil.java:804)
                                                                       at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.execCommand(TransferService.java:300)
                                                                       at com.amazonaws.mobileconnectors.s3.transferutility.TransferService$UpdateHandler.handleMessage(TransferService.java:240)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by kvasukib** [comment] 2018-02-23 22:16
Hi @ushastikin, We have fixed the database connection management bug in the latest update, 2.6.16. Can you please try the latest version and see if that fixes the issue?

**Comment by ipaskhover** [comment] 2018-02-27 22:06
@kvasukib Great news! Thank you!
Unfortunately, I had to switch to another sdk in this project, so I can't check it now (since it happened to me only in production). I will try to use the latest update in my further projects, but not sure how soon it will be.

**Comment by kvasukib** [comment] 2018-02-27 22:34
Thank you @ipaskhover. We are sorry for the inconvenience caused in the past. 2.6.16 should have the stability fixes that could fix this problem. We are working on to improve the TransferUtility as well as the documentation for S3. Please feel free to reach out to us if you run int any problem with TransferUtility.

**Closed by kvasukib** 2018-02-27 22:34 UTC
Labels: S3, pending
