### ISSUE TITLE
Video uploading taken lots of time instead of ios

### ISSUE THREAD

**Issue by moonandroid** [aws/aws-sdk-android#49] opened 2015-06-30 05:51 UTC
We are using video uploading functionality in android and ios.
Both have same function for uploading but in android it taken more time compare to ios
and that is meaning less.
Can you please any solution for this issue ?

**Comment by wdane** [comment] 2015-06-30 18:20
Hey Moonandroid,

Can you fill me in on some additional details?  Are you using the Transfer Manager for either operating system?  What are some example sizes of the video you are uploading?  Are both phones on the same network?  What version of the SDKs are you using?

Thanks!
Weston

**Comment by moonandroid** [comment] 2015-07-01 05:01
#1. I'm using aws-android-sdk-core-2.2.1.jar

#2.Class with used by us:
          Upload upload = tm.upload(request.withCannedAcl(CannedAccessControlList.PublicRead));
                UploadResult result = upload.waitForUploadResult();
                System.out.println("Upload Result"+"-->"+result);
                upload.waitForCompletion();
#3.We are uploading 50MB.
In ios it taken 40-50 second but in android it taken 1.20 minutes with same network.
both have good configuration device.

#4.Are both phones on the same network?
-Yes

**Comment by fosterzhang** [comment] 2015-07-29 18:01
Speed can be affected by various factors, such as network, device hardware, system, application, libraries and some randomness. I don't see enough evidence that AWS Android SDK is the cause of slowness.

**Comment by fosterzhang** [comment] 2015-08-10 00:28
Closing this issue. I don't see a potential implementation issue in the SDK. However, we'll constantly profile the SDK to make sure it's properly optimized.

**Closed by fosterzhang** 2015-08-10 00:28 UTC
