### ISSUE TITLE
S3 Uploads: File gets transferred fully, but status is FAILED

### ISSUE THREAD

**Issue by abdurrahimbliss** [aws/aws-sdk-android#72] opened 2015-10-23 07:29 UTC
I am using the latest TransferUtility to upload files into my S3 bucket. At the end of the transfer, Bytes transferred == Bytes total. And I can see the actual file in the bucket. But the status of the transfer becomes FAILED. I am also getting a call on TransferObserver's onError method. The exception stack trace does not give much clue as well.

java.lang.IllegalStateException: Transfer failed.
	at com.amazonaws.mobileconnectors.s3.transferutility.TransferObserver$TransferContentObserver.onChange(TransferObserver.java:194)
	at android.database.ContentObserver.onChange(ContentObserver.java:129)
	at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:180)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by fosterzhang** [comment] 2015-10-23 22:20
Does it fail all the time? What's the size of the uploaded file? If the file is larger than 5mb, then it will trigger multipart upload. See [Multipart Upload Overview](http://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html). It will go through initiate multipart upload, do actual upload in parts, and complete multipart upload. It's likely that TransferUtility fails on the last step. The problem should go away if you re-upload the file.

**Comment by abdurrahimbliss** [comment] 2015-10-25 02:31
@fosterzhang It happens all the time. Its not multipart upload. The file sizes are ~500kb.

**Comment by fosterzhang** [comment] 2015-10-26 16:32
@abdurrahimbliss I can't reproduce it. Would you please provide these information?
- version of the SDK. The latest one is 2.2.7.
- device/emulator you run the code. Wifi or cellular?
- which S3 region? Any special character in bucket and key. Do you mind share a sample here?
- if possible, would you please provide a code snippet to reproduce the issue?

**Comment by kiranboghra** [comment] 2015-10-28 11:20
@fosterzhang  I also get the same error in cellular network only in WiFi its working very fine please check following Logcat,


11290-11428/com.numberatank W/MetadataResponseHandler﹕ Unable to parse last modified date: Wed,28 Oct 2015 11:09:12 GMT
    java.lang.IllegalArgumentException: java.text.ParseException: Unparseable date: "Wed,28 Oct 2015 11:09:12 GMT" (at offset 4)
            at com.amazonaws.util.DateUtils.parse(DateUtils.java:98)
            at com.amazonaws.util.DateUtils.parseRFC822Date(DateUtils.java:148)
            at com.amazonaws.services.s3.internal.ServiceUtils.parseRfc822Date(ServiceUtils.java:76)
            at com.amazonaws.services.s3.internal.AbstractS3ResponseHandler.populateObjectMetadata(AbstractS3ResponseHandler.java:114)
            at com.amazonaws.services.s3.internal.S3MetadataResponseHandler.handle(S3MetadataResponseHandler.java:34)
            at com.amazonaws.services.s3.internal.S3MetadataResponseHandler.handle(S3MetadataResponseHandler.java:26)
            at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:630)
            at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:365)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
            at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4204)
            at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1111)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.downloadAndWaitForCompletion(DownloadTask.java:83)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:58)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:32)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.text.ParseException: Unparseable date: "Wed,28 Oct 2015 11:09:12 GMT" (at offset 4)
            at java.text.DateFormat.parse(DateFormat.java:579)
            at com.amazonaws.util.DateUtils.parse(DateUtils.java:96)
            at com.amazonaws.util.DateUtils.parseRFC822Date(DateUtils.java:148)
            at com.amazonaws.services.s3.internal.ServiceUtils.parseRfc822Date(ServiceUtils.java:76)
            at com.amazonaws.services.s3.internal.AbstractS3ResponseHandler.populateObjectMetadata(AbstractS3ResponseHandler.java:114)
            at com.amazonaws.services.s3.internal.S3MetadataResponseHandler.handle(S3MetadataResponseHandler.java:34)
            at com.amazonaws.services.s3.internal.S3MetadataResponseHandler.handle(S3MetadataResponseHandler.java:26)
            at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:630)
            at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:365)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
            at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4204)
            at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1111)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.downloadAndWaitForCompletion(DownloadTask.java:83)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:58)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:32)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
10-28 16:48:27.339  11290-11428/com.numberatank W/MetadataResponseHandler﹕ Unable to parse last modified date: Wed,28 Oct 2015 11:09:12 GMT
    java.lang.IllegalArgumentException: java.text.ParseException: Unparseable date: "Wed,28 Oct 2015 11:09:12 GMT" (at offset 4)
            at com.amazonaws.util.DateUtils.parse(DateUtils.java:98)
            at com.amazonaws.util.DateUtils.parseRFC822Date(DateUtils.java:148)
            at com.amazonaws.services.s3.internal.ServiceUtils.parseRfc822Date(ServiceUtils.java:76)
            at com.amazonaws.services.s3.internal.AbstractS3ResponseHandler.populateObjectMetadata(AbstractS3ResponseHandler.java:114)
            at com.amazonaws.services.s3.internal.S3ObjectResponseHandler.handle(S3ObjectResponseHandler.java:51)
            at com.amazonaws.services.s3.internal.S3ObjectResponseHandler.handle(S3ObjectResponseHandler.java:29)
            at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:630)
            at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:365)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
            at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4204)
            at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1272)
            at com.amazonaws.services.s3.AmazonS3Client$1.getS3ObjectStream(AmazonS3Client.java:1378)
            at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:333)
            at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1373)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.downloadAndWaitForCompletion(DownloadTask.java:130)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:58)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:32)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.text.ParseException: Unparseable date: "Wed,28 Oct 2015 11:09:12 GMT" (at offset 4)
            at java.text.DateFormat.parse(DateFormat.java:579)
            at com.amazonaws.util.DateUtils.parse(DateUtils.java:96)
            at com.amazonaws.util.DateUtils.parseRFC822Date(DateUtils.java:148)
            at com.amazonaws.services.s3.internal.ServiceUtils.parseRfc822Date(ServiceUtils.java:76)
            at com.amazonaws.services.s3.internal.AbstractS3ResponseHandler.populateObjectMetadata(AbstractS3ResponseHandler.java:114)
            at com.amazonaws.services.s3.internal.S3ObjectResponseHandler.handle(S3ObjectResponseHandler.java:51)
            at com.amazonaws.services.s3.internal.S3ObjectResponseHandler.handle(S3ObjectResponseHandler.java:29)
            at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:630)
            at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:365)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
            at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4204)
            at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1272)
            at com.amazonaws.services.s3.AmazonS3Client$1.getS3ObjectStream(AmazonS3Client.java:1378)
            at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:333)
            at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1373)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.downloadAndWaitForCompletion(DownloadTask.java:130)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:58)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:32)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
10-28 16:48:27.401  11290-11428/com.numberatank I/ServiceUtils﹕ Retry the download of object channel/4487/3274051446030548213.jpg (bucket img.numbertank.com)
    com.amazonaws.AmazonClientException: Unable to verify integrity of data download.  Client calculated content hash didn't match hash calculated by Amazon S3.  The data may be corrupt.
            at com.amazonaws.services.s3.internal.DigestValidationInputStream.validateMD5Digest(DigestValidationInputStream.java:80)
            at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:62)
            at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
            at java.io.InputStream.read(InputStream.java:162)
            at com.amazonaws.services.s3.internal.ServiceUtils.downloadObjectToFile(ServiceUtils.java:249)
            at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:338)
            at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1373)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.downloadAndWaitForCompletion(DownloadTask.java:130)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:58)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:32)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
10-28 16:48:27.403  11290-11290/com.numberatank D/PPPPPPPPPPPP﹕ 60
10-28 16:48:27.753  11290-11428/com.numberatank W/MetadataResponseHandler﹕ Unable to parse last modified date: Wed,28 Oct 2015 11:09:12 GMT
    java.lang.IllegalArgumentException: java.text.ParseException: Unparseable date: "Wed,28 Oct 2015 11:09:12 GMT" (at offset 4)
            at com.amazonaws.util.DateUtils.parse(DateUtils.java:98)
            at com.amazonaws.util.DateUtils.parseRFC822Date(DateUtils.java:148)
            at com.amazonaws.services.s3.internal.ServiceUtils.parseRfc822Date(ServiceUtils.java:76)
            at com.amazonaws.services.s3.internal.AbstractS3ResponseHandler.populateObjectMetadata(AbstractS3ResponseHandler.java:114)
            at com.amazonaws.services.s3.internal.S3ObjectResponseHandler.handle(S3ObjectResponseHandler.java:51)
            at com.amazonaws.services.s3.internal.S3ObjectResponseHandler.handle(S3ObjectResponseHandler.java:29)
            at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:630)
            at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:365)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
            at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4204)
            at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1272)
            at com.amazonaws.services.s3.AmazonS3Client$1.getS3ObjectStream(AmazonS3Client.java:1378)
            at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:333)
            at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1373)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.downloadAndWaitForCompletion(DownloadTask.java:130)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:58)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:32)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.text.ParseException: Unparseable date: "Wed,28 Oct 2015 11:09:12 GMT" (at offset 4)
            at java.text.DateFormat.parse(DateFormat.java:579)
            at com.amazonaws.util.DateUtils.parse(DateUtils.java:96)
            at com.amazonaws.util.DateUtils.parseRFC822Date(DateUtils.java:148)
            at com.amazonaws.services.s3.internal.ServiceUtils.parseRfc822Date(ServiceUtils.java:76)
            at com.amazonaws.services.s3.internal.AbstractS3ResponseHandler.populateObjectMetadata(AbstractS3ResponseHandler.java:114)
            at com.amazonaws.services.s3.internal.S3ObjectResponseHandler.handle(S3ObjectResponseHandler.java:51)
            at com.amazonaws.services.s3.internal.S3ObjectResponseHandler.handle(S3ObjectResponseHandler.java:29)
            at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:630)
            at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:365)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
            at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4204)
            at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1272)
            at com.amazonaws.services.s3.AmazonS3Client$1.getS3ObjectStream(AmazonS3Client.java:1378)
            at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:333)
            at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1373)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.downloadAndWaitForCompletion(DownloadTask.java:130)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:58)
            at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:32)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)

**Comment by wdane** [comment] 2015-10-29 23:37
I just tried this in Regions.AP_SOUTHEAST_1 on a Nexus 5 uploading and then downloading a 10MB file. I could not reproduce the issue.  Looking at your logs, it looks like the last modified date is in an incorrect format.  Have you perhaps modified this in any way?  Logging the last modified date if I upload and download an object without modifying the last modified at all I see a space after the first comma (in your example I would see.
Wed, 28 Oct 2015 11:09:12 GMT
Instead of 
Wed,28 Oct 2015 11:09:12 GMT

**Comment by abdurrahimbliss** [comment] 2015-11-02 09:50
@fosterzhang
 
* SDK version 2.2.7
* iBall tablet. WiFi
* Region: us-west-2, Bucket name has a dot (.) in the middle. File name has 3 hyphens (-), in addition to the (.) in the file extension. Eg: doctor-doc-733-1446358538786.pdf
*   Code snippet:

	    TransferUtility transferUtility = Utils.getTransferUtility(App.getApp());
            TransferObserver observer = transferUtility.upload(
                    Constants.DOCUMENTS_BUCKET_NAME,
                    mDocument.getFilename(),
                    file
            );
            observer.setTransferListener(new DocumentTransferListener());

            mDocument._awstransferid = observer.getId();

This code executes in onPreExecute of an AsyncTask.

**Comment by fosterzhang** [comment] 2015-11-09 22:45
@abdurrahimbliss As @wdane explained, the SDK failed to parse the the date in the metadata associated with the object. I am not sure whether the metadata is set by the SDK automatically or by you manually. Would you please go to the console to check the metadata of the object? You can find it in object properties. In particular, look for any field that has date in it.

**Comment by fosterzhang** [comment] 2015-12-09 23:41
@abdurrahimbliss After an upload is complete, there is a verification step where the metadata of the upload is read. In your case, the upload is successful, but the verification fails and TransferUtility treats it as failure. The stacktrace shows the error occurs in parsing the last modified date in the metadata header. Per [Amazon S3's documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html), this field is set by the service. For some reason, the date is malformed. Please go to the console to double check the exact date string. I believe it's a single incident. If this happens again, please reopen the issue.

**Comment by fosterzhang** [comment] 2015-12-09 23:41
Closing this as it's not reproducible.

**Closed** 2015-12-10 00:20 UTC
Labels: question

**Comment by davidhowe** [comment] 2017-08-01 13:48
I'm also experiencing this issue with SDK v2.4.5
On first upload attempt, upload fails, then on a retry the successive files are all uploaded.

File sizes range from 250B to 600KB

**Comment by perlics** [comment] 2020-05-28 09:57
It also started happening to me randomly on Android. Any fixes?
