### ISSUE TITLE
 java.net.UnknownHostException: Unable to resolve host "lambda.ap-northeast-1.amazonaws.com"

### ISSUE THREAD

**Issue by billywong4d** [aws/aws-sdk-android#251] opened 2017-02-08 02:29 UTC
Hi,

  I have a launched android game and some of our user randomly hit the following error. Please give me some insight on how to resolve this. Thank you!

java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:299)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:856)
Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "lambda.ap-northeast-1.amazonaws.com": No address associated with hostname
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:424)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:419)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:364)
	at com.amazonaws.mobileconnectors.lambdainvoker.LambdaInvocationHandler.invoke(LambdaInvocationHandler.java:62)
	at $Proxy0.recordPlayerAction(Native Method)
	at org.cocos2dx.cpp.AndroidAwsManager$29.doInBackground(AndroidAwsManager.java:1723)
	at org.cocos2dx.cpp.AndroidAwsManager$29.doInBackground(AndroidAwsManager.java:1717)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	... 4 more
Caused by: java.net.UnknownHostException: Unable to resolve host "lambda.ap-northeast-1.amazonaws.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:394)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
	at java.net.InetAddress.getAllByName(InetAddress.java:214)
	at libcore.net.http.HttpConnection.<init>(HttpConnection.java:70)
	at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
	at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
	at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:316)
	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:461)
	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:442)
	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
	at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
	at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
	at libcore.net.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:281)
	at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:128)
	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:356)

Thank you!

**Comment by minbi** [comment] 2017-02-08 04:23
Hi @billywong4d,

Can you provide any reproduction steps? Do any network calls succeed before this error?
Could these users have blocked the app from accessing the internet?

**Comment by ankitpise** [comment] 2017-02-13 19:18
It is true that lot of times it fails to resolve dns for the first time with lambda and API gateway.

**Comment by karthiksaligrama** [comment] 2017-03-07 16:49
can you confirm if you are on a stable network?

**Comment by karthiksaligrama** [comment] 2017-03-12 06:32
Unable to reproduce, closing.If you have steps to reproduce feel free to reopen/ open a new issue.

**Closed by karthiksaligrama** 2017-03-12 06:32 UTC

**Comment by prabha303** [comment] 2018-02-15 05:35
I am also facing same issue with AWS Lambda.
