### ISSUE TITLE
[Kinesis Streams] Partition key is not different for records within a single batch.

### ISSUE THREAD

**Issue by GingerNinja23** [aws/aws-sdk-android#533] opened 2018-09-21 05:38 UTC
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Kinesis

* In what version of SDK are you facing the problem?
2.3.x

* Is the issue limited to Simulators / Actual Devices?
Actual devices

* Can your problem be resolved if you bump to a higher version of SDK?
No, the issue is present in the latest version of the SDK as well.

* Is this problem related to specific Android/OS version?
No.

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Not applicable

* Please include a stacktrace if applicable.
Not applicable

--------------------------------------------------

In the current implementation of KinesisRecorder, when a partition key is not explicitly specified in the KinesisRecorderConfig, the [same randomly-generated partition key is set to all records within a batch of records](https://github.com/aws/aws-sdk-android/blob/1d492dc7d8ad37a14596ddc337ba1a0733ec1182/aws-android-sdk-kinesis/src/main/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/KinesisStreamRecordSender.java#L80). This is leading to the records not being distributed equally among the shards, and also increased throttling of write requests to the stream with the 'WriteprovisionedThroughputExceeded' exception. The implementation should be changed to generate a random partition key for each record.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by sunchunqiang** [comment] 2018-09-27 22:06
The issue is fixed in AWS SDK for Android 2.7.3. Please update your Android AWS SDK to 2.7.3, let's know if it's not fixed correctly

**Closed** 2018-09-27 22:17 UTC
Labels: Kinesis

**Comment by GingerNinja23** [comment] 2018-09-28 07:49
Thanks Frank! We'll give the latest version a try, and let you know how things work.
