### ISSUE TITLE
GaiException in com.amazonaws.http.AmazonHttpClient.executeHelper

### ISSUE THREAD

**Issue by lycha** [aws/aws-sdk-android#174] opened 2016-07-15 08:11 UTC
Hello everyone,
have you ever encountered following exception while using AWS SDK?

`Android: 6.0.1
Android Build: MMB29V
Manufacturer: htc
Model: Nexus 9
Thread: Thread-148-148

com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.us-east-1.amazonaws.com": No address associated with hostname
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:421)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:533)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:406)
	at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:627)
	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:553)
	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:370)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:440)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:76)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:3245)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:965)
	at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper$SaveObjectHandler.doUpdateItem(DynamoDBMapper.java:1173)
	at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper$2.executeLowLevelRequest(DynamoDBMapper.java:873)
	at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper$SaveObjectHandler.execute(DynamoDBMapper.java:1056)
	at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.save(DynamoDBMapper.java:904)
	at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.save(DynamoDBMapper.java:688)
	at co.netguru.android.poscitibike.network.aws.SaveAwsLogoutService$1$1.run(SaveAwsLogoutService.java:64)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.UnknownHostException: Unable to resolve host "cognito-identity.us-east-1.amazonaws.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
	at java.net.InetAddress.getAllByName(InetAddress.java:215)
	at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
	at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
	at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:128)
	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
	... 17 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Posix.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
	... 35 more
 `

**Comment by fosterzhang** [comment] 2016-07-16 01:26
@lycha This is usually caused by network issue. Something to check:
- make sure your app has permission to access internet. Add this line to `AndroidManifest.xml`: `<uses-permission android:name="android.permission.INTERNET" />`.
- check whether your device/emulator has network connection. Make sure it's not in airplane mode. Try hitting some popular site like http://www.google.com in web browser.
- Open https://cognito-identity.us-east-1.amazonaws.com in a web browser. You will be redirect to https://aws.amazon.com/cognito/. This is to check whether Cognito is blocked by firewall.
- Reopen the app to see if the problem goes away on a second try.
- Reboot the device. Sometimes the DNS cache has incorrect entries. Rebooting can clear it.

**Comment by lycha** [comment] 2016-07-18 07:01
@fosterzhang thank you for your answer. I'm aware of the configuration issues that may encounter during working with online resources. Let me specify the problem. I have an app produced for the client that connects with DynamoDB. It's working on the production for almost 2 months right now and I got this error once on production device. We didn't encounter any problems before and during intensive QA testing. I just want to make sure that the app will not crash because of this error in future. What's more methods I use form SDK are not declared as throwing GaiException. In my opinion it's not the good case practice that an app crashes because of unspecified exception when network is not available.

**Comment by fosterzhang** [comment] 2016-07-18 22:23
@lycha `GaiException` is thrown by the system trying to resolve a host name. More often, we see `UnknownHostException`. In each service API call, the SDK try catches all exceptions and turns them into `AmazonClientException`, which is a runtime (unchecked) exception for legacy reasons. The exception is declared in the method signature, but it's not prompted in IDE due to the fact that it's an unchecked exception. It's hard to say whether the exception should be a checked exception or not (see [Exception Handling](http://docs.aws.amazon.com/java-sdk/latest/developer-guide/java-dg-exceptions.html)).

Nevertheless, to prevent the app from crashing, I suggest you put a try catch block of `AmazonClientException` around critical code paths. If the problem occurs frequently and can be reproduced reliably, please let us know. We'll look into the problem further.

**Comment by lycha** [comment] 2016-07-19 07:26
@fosterzhang Thank you for the information. We will investigate this further and come back if we have more specific data.

**Comment by wdane** [comment] 2016-09-08 21:43
Appears resolved, closing.

**Closed by wdane** 2016-09-08 21:43 UTC
Labels: question

**Comment by rakesh-3607** [comment] 2016-10-21 13:14
We are having the same problem of unknown host exception. 

We are calling this from our Java Server - Which has a Stable connection. 
And We are able to call to the cognito identity server from the Localhost but not from our Server.

Can you please help to let me know what could be the issue ?

Regards,
Rakesh
