### ISSUE TITLE
SSL Handshake Failed/Timeout

### ISSUE THREAD

**Issue by nikeshbhawsar** [aws/aws-sdk-android#133] opened 2016-05-13 10:02 UTC
Hi,

We are facing frequent SSL connection handshake failed/timeout, while uploading object to S3. Our use case is to upload object on S3 every 30 seconds. This issue is resulting in data loss.

This issue faced only after upgrading to new AWS libraries. Earlier we were using the aws library jar version 1.7.1.1 and it was working fine.

**Library Used**: AWS android sdk 2.2.16 . 

**Devices Used**: Tablet with android version 4.0.4 and 5.1.1

Code snippet.
**S3 Instantiation and putObject**:
```
 AmazonS3Client sS3Client = new AmazonS3Client(new BasicAWSCredentials(key,secretKey));
 sS3Client.setRegion(com.amazonaws.regions.Region.getRegion(Regions.US_EAST_1));

 PutObjectResult result = sS3Client.putObject(Constants.BUCKET_NAME, Long.toString(new Date().getTime()), is, metaData);
```

Above line throws following exception intermittently, which causing data packet loss.

**StackTrace**

	Unable to execute HTTP request: failed to connect to wmobugpsnonprod.s3.amazonaws.com/54.231.81.8 (port 443) after 15000ms
	com.amazonaws.AmazonClientException: Unable to execute HTTP request: failed to connect to 		wmobugpsnonprod.s3.amazonaws.com/54.231.81.8 (port 443) after 15000ms

 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:428)

 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)

 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221)

 	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1628)

 	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1457)

 	at com.wm.ocs.android.da.service.aws.AWSGPSPingUploader.uploadGPSPing(AWSGPSPingUploader.java:196)

 	at com.wm.ocs.android.da.service.aws.AWSGPSPingUploader.access$1(AWSGPSPingUploader.java:102)

 	at com.wm.ocs.android.da.service.aws.AWSGPSPingUploader$UploadTask.doInBackground(AWSGPSPingUploader.java:352)

 	at com.wm.ocs.android.da.service.aws.AWSGPSPingUploader$UploadTask.doInBackground(AWSGPSPingUploader.java:1)

 	at android.os.AsyncTask$2.call(AsyncTask.java:264)

 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)

 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)

 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)

 	at java.lang.Thread.run(Thread.java:856)

	Caused by: java.net.SocketTimeoutException: failed to connect to wmobugpsnonprod.s3.amazonaws.com/54.231.81.8 (port 443) after 15000ms

 	at libcore.io.IoBridge.connectErrno(IoBridge.java:150)

 	at libcore.io.IoBridge.connect(IoBridge.java:112)

 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)

 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)

 	at java.net.Socket.connect(Socket.java:848)

 	at libcore.net.http.HttpConnection.<init>(HttpConnection.java:77)

 	at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)

 	at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:351)

 	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:86)

 	at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)

 	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:308)

 	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:460)

 	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:441)

 	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:282)

 	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:232)

 	at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)

 	at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:188)

 	at libcore.net.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:280)

 	at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:128)

 	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)

 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360)

 	... 15 more

**Comment by fosterzhang** [comment] 2016-05-13 14:45
@nikeshbhawsar the default connection timeout and socket timeout have been reduced from 60s (or 120s) to 15s. You can change it via `ClientConfiguration.setConnectionTimeout(int ms)`.

**Comment by nikeshbhawsar** [comment] 2016-05-16 09:28
@fosterzhang Even I tried inceasing the ConnectionTimeout via ClientConfiguration.setConnectionTimeout(int ms), but still getting the same error.

**Comment by fosterzhang** [comment] 2016-05-16 18:52
@nikeshbhawsar What value did you set? And what is the error message?

**Comment by fosterzhang** [comment] 2016-05-27 06:37
Closing this. Feel free to reopen this.

**Closed by fosterzhang** 2016-05-27 06:37 UTC
Labels: question

**Comment by anilshar** [comment] 2016-06-09 11:56
Hi @fosterzhang 

I have also faced this issue while implementing photo/video upload from android device to s3 bucket. 

This is an intermittent issue and it can be observed on both mobile & wifi with good internet connection. 

This is how I have done Amazon s3 client initialization 
  /**
     * Gets an instance of CognitoCachingCredentialsProvider which is
     * constructed using the given Context.
     *
     * @return A default credential provider.
     */
    private static CognitoCachingCredentialsProvider getCredProvider() {
        if (sCredProvider == null) {
            ClientConfiguration clientConfiguration = new ClientConfiguration();
            clientConfiguration.setConnectionTimeout(250000);
            clientConfiguration.setSocketTimeout(250000);
            sCredProvider = new CognitoCachingCredentialsProvider(
                    MyApplication.applicationContext,
                    COGNITO_POOL_ID,
                    Regions.US_EAST_1,
                    clientConfiguration);
        }
        return sCredProvider;
    }

    /**
     * Gets an instance of a S3 client which is constructed using the given
     * Context.
     *
     * @return A default S3 client.
     */
    private static AmazonS3Client getS3Client() {
        if (sS3Client == null) {
            sS3Client = new AmazonS3Client(getCredProvider());
        }
        return sS3Client;
    }

**Comment by anilshar** [comment] 2016-06-09 11:57
com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
                                                                                at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:428)
                                                                                at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
                                                                                at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221)
                                                                                at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1628)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:205)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:86)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:45)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
                                                                             Caused by: java.net.SocketTimeoutException: timeout
                                                                                at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:207)
                                                                                at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
                                                                                at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                                                at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                                                at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                                                at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                                                at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
                                                                                at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                                                                at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
                                                                                at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
                                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
                                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:497)
                                                                                at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
                                                                                at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java)
                                                                                at com.newrelic.agent.android.instrumentation.HttpsURLConnectionExtension.getResponseMessage(HttpsURLConnectionExtension.java:251)
                                                                                at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72)
                                                                                at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66)
                                                                                at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360)
                                                                                at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
                                                                                at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221)
                                                                                at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1628)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:205)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:86)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:45)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)

**Comment by tomdabr** [comment] 2017-04-21 15:03
Hi @anilshar 
Did you manage to find out what caused this issue?
I am facing the same problem (intermittent "connect timed out" errors).

**Comment by Qamar4P** [comment] 2017-08-11 10:02
Same issue
```
com.amazonaws.AmazonClientException: Unable to execute HTTP request: SSL handshake aborted: ssl=0x60c587c8: I/O error during system call, Connection reset by peer
                                                                               at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
                                                                               at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                                                                               at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:559)
                                                                               at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:445)
                                                                               at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
```

then add this code before call
```
try {
			SSLContext.getInstance("TLSv1.2");
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}
		try {
			ProviderInstaller.installIfNeeded(mContext.getApplicationContext());
		} catch (GooglePlayServicesRepairableException e) {
			e.printStackTrace();
		} catch (GooglePlayServicesNotAvailableException e) {
			e.printStackTrace();
		}
```

then got 
`AmazonClientException: Unable to execute HTTP request: Hostname 'cognito-identity.ap-northeast-1.amazonaws.com' was not verified` 
confused!!!
