### ISSUE TITLE
SDK doesn't upload .mp4 correctly in multiple parts 

### ISSUE THREAD

**Issue by Gelassen** [aws/aws-sdk-android#46] opened 2015-06-19 04:38 UTC
I am trying to upload item from Android client to China bucket. It is ~20 seconds video (~50mb) with hight resolution.  It is separated in multiple chunks and each of them successfully uploaded: 
   - I receive ProgressEvent.PART_COMPLETED_EVENT_CODE for all of them
   - I track how much bytes are transfered and it fully reach the size of the video

When I receive the last ProgressEvent.PART_COMPLETED_EVENT_CODE SDK stops send any events codes -- looks like it done his job. I checked the data on the server but got an error "NoSuchKey"

Observed behaviour: 
SDK doesn't return ProgressEvent.COMPLETED_EVENT_CODE. Amazon via web request returns "NoSuchKey" error  

Expected behaviour: 
SDK returns ProgressEvent.COMPLETED_EVENT_CODE. Amazon via web request returns uploaded video. 

Environment:
Nexus 5, Android 5.1
AWS SDK 2.2.2
Region "cn-north-1"

**Comment by wdane** [comment] 2015-06-23 20:45
Sorry for the late reply.  I'm having trouble reproducing the issue.  Are you sure the key you are using on your server is the same key that your app is sending??  If so, it could cause a NoSuchKey error.

I tried the following and was able to download the file from the console.

private class LargeChinaUpload extends AsyncTask<Void, Void, Void> {

        @Override
        protected Void doInBackground(Void... params) {
            s3.setRegion(Region.getRegion(Regions.CN_NORTH_1));

            // create large file
            File largeFile = null;
            try {
                File dir = MainActivity.this.getDir("BJSTest", Context.MODE_PRIVATE);
                largeFile = new File(dir, "deleteMe");
                largeFile.deleteOnExit();

                Random r = new Random();
                // 1Mb
                byte[] buff = new byte[1024000];
                r.nextBytes(buff);
                FileOutputStream fos = new FileOutputStream(largeFile);
                for (int i = 0; i < 40; i++) {
                    fos.write(buff);
                }

                // Try to upload to BJS
                TransferManager tm = new TransferManager(s3);
                Log.d(TAG, "Beginning upload");
                Upload upload = tm.upload("testbucket", "largebjsfiletest", largeFile);
                upload.addProgressListener(new ProgressListener() {

                    int total = 0;

                    @Override
                    public void progressChanged(ProgressEvent progressEvent) {
                        Log.d(TAG, "ProgressEvent: " + progressEvent.getEventCode());
                        if (progressEvent.getEventCode() == ProgressEvent.COMPLETED_EVENT_CODE) {
                            Log.d(TAG, "completed!");
                        }
                        Log.d(TAG,
                                "ProgressEvent: transferred: "
                                        + progressEvent.getBytesTransferred());
                        Log.d(TAG,
                                "ProgressEvent: total: "
                                        + (total += progressEvent.getBytesTransferred()));
                    }

                });
                AmazonClientException ace = upload.waitForException();

                if (ace == null) {
                    Log.d(TAG, "upload finished, No Errors");
                } else {
                    Log.e(TAG, "upload failed, error", ace);
                }
                return null;
            } catch (IOException e) {
                Log.e(TAG, "IOE:", e);
            } catch (InterruptedException e) {
                Log.e(TAG, "interrupted");
            } finally {
                if (largeFile != null && largeFile.exists()) {
                    largeFile.delete();
                }
            }
            return null;
        }
    }

**Comment by Gelassen** [comment] 2015-06-24 01:44
Yes, I confirm keys are correct. 

At this moment I increase threshold to 1gb when AWS SDK turn on multiple chunks upload but it is temporary workaround -- multiple chunks upload is broken at least for cn-north-1 region. 

If you would like to see details we can organize sharing screen session. 

I understand it looks strange when dev submit a report and insist this is a bug in the SDk rather than his own bug but China has a lot of surprises and I already pointed out on another bug where certain headers aren't signed so please bring close attention to this possibility.

**Comment by oliviapryor** [comment] 2015-06-24 22:07
I'm encountering the same behavior. Smaller mp4 files are uploaded in one part and receive a COMPLETED_EVENT_CODE. Larger mp4 files are being transmitted in multiple parts, and I receive a PART_COMPLETED_EVENT_CODE for each but no COMPLETED_EVENT_CODE for the overall transfer.

**Comment by wdane** [comment] 2015-06-25 00:49
@Gelassen Can you please see add some sample code that shows how what you are doing is different than the code I posted above.  Definitely would like to help you on this.

@oliviapryor Is the upload actually working? (As in can be downloaded afterwards)

**Comment by Gelassen** [comment] 2015-06-25 01:00
@wdane, please see my code below:
```
    public static Upload upload(final MediaItem mediaItem, S3ProgressListener listener) {
        // set up credentials
        AwsMetadata awsMetadata = mediaItem.getAwsMetadata();
        AWSCredentials awsCredentials = new BasicAWSCredentials(
                awsMetadata.getAccountId(),
                awsMetadata.getSecretKey()
        );
        File file = new File(mediaItem.getContentUri());
        Log.d(App.TAG, "Files exists: " + file.toString() + " " + file.exists());
        // set up request
        PutObjectRequest request = new PutObjectRequest(
                awsMetadata.getBucketName(),
                awsMetadata.getUuid().concat(FileUtil.extractPrefixFromPath(mediaItem.getContentUri())),
                file
        );

        TransferManagerConfiguration transferManagerConfiguration = new TransferManagerConfiguration();
        transferManagerConfiguration.setMultipartUploadThreshold(1073741824); // 1 gb threshold

        TransferManager transferManager = new TransferManager(awsCredentials);
        transferManager.setConfiguration(transferManagerConfiguration);
        transferManager.getAmazonS3Client().setRegion(getRegionForMedia(awsMetadata));
        return transferManager.upload(request, listener);
    }
```

I use our own server to obtain credentials and this scredentials wraped by AwsMetadata

**Comment by wdane** [comment] 2015-06-25 17:59
@Gelassen @oliviapryor 
Thanks for the code snippet Gelassen.  With it I am able to reproduce the error you guys are observing.  I will be looking into it to see if I can find a solution, and get back to you guys.

**Comment by wdane** [comment] 2015-06-25 20:23
@Gelassen  @oliviapryor 
Hey guys, it looks like you can get around the issue by calling upload.waitForCompletion() (upload.waitForException() also worked for me).  It appears there is some faulty logic if those methods are not called.  I will add this bug to our backlog, for now calling waitFor... should work for the time being.  I'll leave this issue open until a full fix is implemented.

Thanks,
Weston

**Comment by wdane** [comment] 2015-07-01 19:21
Okay guys,

It turns out the reason this is happening, is that the TransferManager class implements finalize() which upon garbage collection shuts down the thread pools it is using for transfers when it is being garbage collected.  Internally the Transfer Manager uses these thread pools for checking to see if all multi-part uploads have been completed, and when they have, call the complete multi-part upload API for S3.  However in the example code above Transfer Manager is going out of scope prior to the transfer completing, which causes the code to never complete the multi-part upload because the thread pool it uses to schedule tasks is shutdown.  I'm closing this issue for now, and will update the javadoc to say as much.  But the solution is to keep a reference to TransferManager for at least as long as the upload is going on.  All transfers have an isDone() method which can make this check.

Sorry for the confusion,
Weston

**Closed by wdane** 2015-07-01 19:21 UTC
Labels: bug
