### ISSUE TITLE
Upload does not resume using  aws-android-sdk-2.2.3-s3

### ISSUE THREAD

**Issue by suraj9781** [aws/aws-sdk-android#44] opened 2015-06-12 05:13 UTC
Hi there,

For Low level api:
I am using low level api for multipart upload .When i kill the app and try to resume upload it doesnot resume instead it restarts .When i try resume the upload i am getting different upload id for same key and bucket.
When tried to store the upload id obtain when i start upload and try to used that upload id first time upload resumed but it did not complete.I got following error exception:
06-11 16:55:51.374  22136-22388/com.sharez D/UploadObjectMPU﹕ Error !!! :: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag. (Service: Amazon S3; Status Code: 400; Error Code: InvalidPart; Request ID: 264F4CFFAE836648)

Second time:
Upload did not resume and i got following error:
06-12 11:09:39.108    7160-7222/com.sharez D/UploadObjectMPU﹕ Error !!! :: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: AAD7BBFAB6F5402B)
 
.Following is the code used.

/**
	 * This method is useful to resume update
	 * 
	 * @param pInitResponse
	 * @param pS3Client
	 * @param pPartETags
	 * @return
	 */
	private int retrievePartDetails(
			InitiateMultipartUploadResult pInitResponse,
			AmazonS3Client pS3Client, List<PartETag> pPartETags) {
		// for new upload this upload id may be null or empty for paused upload
		// this has some values
		String  lUploadId =pInitResponse.getUploadId();
		Log.d(TAG, "retrievePartDetails():   uploadId = " + lUploadId);
		ListPartsRequest lPartsRequest = new ListPartsRequest(mBucketName,
				mKeyName, lUploadId);
		PartListing lListing = pS3Client.listParts(lPartsRequest);
		List<PartSummary> lList = lListing.getParts();

		for (PartSummary lPartSummary : lList) {
			PartETag lPartETag = new PartETag(lPartSummary.getPartNumber(),
					lPartSummary.getETag());
			pPartETags.add(lPartETag);
		}

		return (lList.size() < 1) ? 1 : lList.get(lList.size() - 1)
				.getPartNumber() + 1;
	}

/**
	 * get a upload request
	 * 

	 * 
	 * @return
	 */

private InitiateMultipartUploadRequest getUploadRequest() {

		return new InitiateMultipartUploadRequest(mBucketName, mKeyName);
		// return new InitiateMultipartUploadRequest(mBucketName, mKeyName);
	}

	/**
	 * Intiate mutipart request
	 * 
	 * @param pS3LowLevelUploadTask
	 * @param pFile
	 */
private void initateMutipartRequest(
			S3LowLevelUploadTask pS3LowLevelUploadTask, File pFile) {
		// Create a list of UploadPartResponse objects. You get one of these
		// for each part upload.
		List<PartETag> lPartETags = new ArrayList<PartETag>();
		try {

			mInitResponse = mS3Client
					.initiateMultipartUpload(getUploadRequest());

			// required for resume
			int lStartPart = retrievePartDetails(mInitResponse, mS3Client,
					lPartETags);
			Log.d(TAG, "lStartPart = " + lStartPart);

			long lFilePosition = (lStartPart - 1) * mPartSize;
			Log.d(TAG, "filePosition = " + lFilePosition);
			// show default progress for multipart upload
			

			for (int i = lStartPart; lFilePosition < mFileSize; i++) {

				
				// Last part can be less than 5 MB. Adjust part size.
				mPartSize = Math.min(mPartSize, (mFileSize - lFilePosition));

				// Create request to upload a part.
				mUploadRequest = new UploadPartRequest()
						.withBucketName(mBucketName).withKey(mKeyName)
						.withUploadId(mInitResponse.getUploadId())
						.withPartNumber(i).withFileOffset(lFilePosition)
						.withFile(pFile).withPartSize(mPartSize)
						.withGeneralProgressListener(this);

				// Upload part and add response to our list.
				lPartETags.add(mS3Client.uploadPart(mUploadRequest)
						.getPartETag());
				lFilePosition += mPartSize;
				// request update percentage to UI

				pS3LowLevelUploadTask.updateProgress(getPercentageUpload(
						mFileSize, lFilePosition));
				Log.d(TAG, "filePosition = " + lFilePosition);

			}

			
				perfromComplete(mInitResponse, lPartETags, mS3Client);
				
				

			

		} catch (AbortedException lAse) {
			lAse.printStackTrace();
		} catch (Exception e) {
			Log.d(TAG, "Error !!! :: " + e.getMessage());
			e.printStackTrace();
		
		}
		
	}

/**
	 * Mark file has been successfully uploaded
	 * 
	 * @param pInitResponse
	 * @param pPartETags
	 * @param pS3Client
	 * @param pS3LowLevelUploadTask
	 */
	private void perfromComplete(InitiateMultipartUploadResult pInitResponse,
			List<PartETag> pPartETags, AmazonS3Client pS3Client) {
		CompleteMultipartUploadRequest compRequest = new CompleteMultipartUploadRequest(
				mBucketName, mKeyName, pInitResponse.getUploadId(), pPartETags);
		pS3Client.completeMultipartUpload(compRequest);

	}

For high level api:

/**To save transfer state*/
public void saveTransferState(PersistableTransfer persistableTransfer, String fileName) {
  // Create a new file to store the information.
  File f = new File(fileName);
  if( !f.exists() ) f.createNewFile();
  FileOutputStream fos = new FileOutputStream(f);
  // Serialize the persistable transfer to the file.
  persistableTransfer.serialize(fos);
  fos.close();    
}

PutObjectRequest putRequest = new PutObjectRequest(BUCKET_NAME, mKey,file);
// Upload a file to Amazon S3.
transferManager.upload(putRequest, new S3ProgressListener() {
  ExecutorService executor = Executors.newFixedThreadPool(1);
  @Override
  public void onPersistableTransfer(final PersistableTransfer persistableTransfer) {
        executor.submit(new Runnable() {
          @Override
          public void run() {
              saveTransferState(persistableTransfer, “resume-upload”);
          }
        });
    }
});

For resuming upload:

String fileName = "resume-upload";
File f = new File (fileName);
if(f.exists()) {
  FileInputStream fis = new FileInputStream(f); 
  // Deserialize PersistableUpload information from disk. 
  PersistableUpload persistableUpload = PersistableTransfer.deserializeFrom(fis); 
  // Call resumeUpload with PersistableUpload. 
 mUpload =  transferManager.resumeUpload(persistableUpload); 
try {

			if (mUpload != null) {

				mUpload.addProgressListener(this);

				mUpload.waitForCompletion();

			}
		}

		catch (AmazonServiceException e) {

			e.printStackTrace();

		} catch (AmazonClientException e) {

			e.printStackTrace();

		} catch (InterruptedException e) {

			e.printStackTrace();

		} catch (Exception e) {
			e.printStackTrace();
		}
	}
  fis.close();
}

**Comment by suraj9781** [comment] 2015-06-30 04:02
Hey... do you have any updates on this?

**Comment by wdane** [comment] 2015-07-01 23:19
This is a little too much code for me to go over... can you create a small example showing the error?  I'm not sure if you are trying to combine using the Transfer Manager and the low level, or trying both and neither are working.

Thanks.

**Comment by suraj9781** [comment] 2015-07-02 04:49
I tried both and neither of them is working 
1) Using low level upload i tried to retrieve part for resume following function but it always returns 1: 

private int retrievePartDetails(InitiateMultipartUploadResult pInitResponse,AmazonS3Client pS3Client, List pPartETags) {
// for new upload this upload id may be null or empty for paused upload
// this has some values
String lUploadId =pInitResponse.getUploadId();
Log.d(TAG, "retrievePartDetails(): uploadId = " + lUploadId);
ListPartsRequest lPartsRequest = new ListPartsRequest(mBucketName,
mKeyName, lUploadId);
PartListing lListing = pS3Client.listParts(lPartsRequest);
List lList = lListing.getParts();

    for (PartSummary lPartSummary : lList) {
        PartETag lPartETag = new PartETag(lPartSummary.getPartNumber(),
                lPartSummary.getETag());
        pPartETags.add(lPartETag);
    }

    return (lList.size() < 1) ? 1 : lList.get(lList.size() - 1)
            .getPartNumber() + 1;
}


2)Please refer following link for transfermanager 
http://mobile.awsblog.com/post/TxGY67VAIX09HV/Pause-and-Resume-Amazon-S3-Transfers-Using-the-AWS-Mobile-SDK-for-Android

It works for download and not for upload

**Comment by wdane** [comment] 2015-07-03 00:54
Sorry about this issue, I've fixed and verified the transfer manager and it will be available in a new release soon.  In the mean time, you can resolve this issue, by using a GetObjectRequest with transferManager.download() and specifying the range of the full item.  So if the item in S3 is 1000 bytes, then doing getObjectRequst.setRange(0, 1000);  should work.  If you don't know the size of the object you can do a GetObjectMetadataRequest and then call metadata.getContentLength() to find out.

Will leave this issue open until we make a release to properly fix it.

**Comment by suraj9781** [comment] 2015-07-03 04:37
Hey wdane,

Is this fix available for upload because i have issue with upload and not download.

**Comment by wdane** [comment] 2015-07-13 20:01
The fix should be available with release 2.2.3, which is now available on the website.  Please re-open if this does not resolve your issue.

**Comment by suraj9781** [comment] 2015-07-14 04:57
Re opening issue .I have issue with upload  resume which is still not fixed in 2.2.3.

**Comment by wdane** [comment] 2015-07-16 00:37
I can't seem to reproduce your issue.  Testing with the latest SDK this works for me

downloadedData is where I have the data I'm uploading.'
resumeInfo the file where I'm serializing the upload

 Upload upload = tm
                    .upload(BUCKET, KEY, downloadedData);
            while ((transferred = upload.getProgress().getBytesTransferred()) < (10 * Constants.MB)) {
                System.out.println("Waiting for more data to upload, currently uploaded : "
                        + upload.getProgress().getBytesTransferred());
                Thread.sleep(1000);
            }
            PersistableUpload pausedUpload = upload.pause();
            resumeInfo.delete();
            resumeInfo.createNewFile();

            resumeFos = new FileOutputStream(resumeInfo);
            resumeFis = new FileInputStream(resumeInfo);
            pausedUpload.serialize(resumeFos);

            PersistableUpload serializedUpload = PersistableUpload.deserializeFrom(resumeFis);
            System.out.println("Resuming upload");
            Upload resumedUpload = tm.resumeUpload(serializedUpload);

            while (!resumedUpload.isDone()) {
                Thread.sleep(1000);
                System.out.println("Resumed Upload has transferred: "
                        + resumedUpload.getProgress().getBytesTransferred() + " / "
                        + resumedUpload.getProgress().getTotalBytesToTransfer());
            }

            resumeFos.close();
            resumeFis.close();

            System.out.println("Resumed upload completed successfully");

**Comment by suraj9781** [comment] 2015-07-16 08:31
The below method gets callback only once 
 @Override
    public void onPersistableTransfer(PersistableTransfer pPersistableTransfer) {
      saveTransferState(persistableTransfer, “resume-upload”);
}

**Comment by wdane** [comment] 2015-07-17 18:46
That is intended behavior.  The persistable transfer you receive is good for the life of the transfer.  So in other words, if you persist the transfer when it begins, and it crashes half way through, that serialized transfer can be used to resume the transfer from the 1/2 way point you left off at (specifically it will re-transfer any non-completed parts).  So there is no need for this callback to be fired multiple times

**Comment by suraj9781** [comment] 2015-07-20 08:55
Ok.But using  that serialize object upload doesn't resume for me but it restarts.


    //Code for resuming upload
           FileInputStream   lFis = new FileInputStream(lfile);
            // Deserialize PersistableUpload information from disk.

            PersistableUpload lPersistableUpload = PersistableTransfer
                    .deserializeFrom(lFis);

            // Call resumeUpload with PersistableUpload.
            mUpload = mTransferManager.resumeUpload(lPersistableUpload);
           
            lFis.close();

           mUpload.waitForCompletion();

**Comment by wdane** [comment] 2015-07-20 18:07
Do you know how much data has been uploaded when you pause?  The transfer manager uses multipart uploads, and uploads in parallel.  Pausing throws away any partially completed parts, and retains any completed parts.  So if no parts have actually completed then pausing is effectively a cancel.

**Comment by suraj9781** [comment] 2015-07-21 05:38
No because i don't pause it using "upload.pause()" .The PersistableTransfer object is only saved in 
onPersistableTransfer(PersistableTransfer pPersistableTransfer).

**Comment by wdane** [comment] 2015-07-22 23:28
For now I am closing this issue.  Today the Transfer Manager was deprecated, with the release of the Transfer Utility.  For help using the Transfer Utility see our blog post, getting started guide, tutorial, and sample.

http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/s3transferutility.html
https://github.com/awslabs/aws-sdk-android-samples
https://mobile.awsblog.com/post/Tx16PLJMWD1K9ZX/Introducing-the-Transfer-Utility-for-the-AWS-SDK-for-Android
https://mobile.awsblog.com/post/Tx2KF0YUQITA164/AWS-SDK-for-Android-Transfer-Manager-to-Transfer-Utility-Migration-Guide

**Closed by wdane** 2015-07-22 23:28 UTC
Labels: bug

**Comment by suraj9781** [comment] 2015-07-27 05:53
Hey wdane,

What about low level api it upload  doesnot resume using that also.
This always returns 1.
private int retrievePartDetails(
InitiateMultipartUploadResult pInitResponse,
AmazonS3Client pS3Client, List pPartETags) {
// for new upload this upload id may be null or empty for paused upload
// this has some values
String lUploadId =pInitResponse.getUploadId();
Log.d(TAG, "retrievePartDetails(): uploadId = " + lUploadId);
ListPartsRequest lPartsRequest = new ListPartsRequest(mBucketName,
mKeyName, lUploadId);
PartListing lListing = pS3Client.listParts(lPartsRequest);
List lList = lListing.getParts();

    for (PartSummary lPartSummary : lList) {
        PartETag lPartETag = new PartETag(lPartSummary.getPartNumber(),
                lPartSummary.getETag());
        pPartETags.add(lPartETag);
    }

    return (lList.size() < 1) ? 1 : lList.get(lList.size() - 1)
            .getPartNumber() + 1;
}
