### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by nikeshbhawsar** [aws/aws-sdk-android#195] opened 2016-09-14 06:40 UTC
Hi Team,
Could you please look into the folllowing issue.
We are receiving below error while uploading data to S3.

> com.amazonaws.AmazonClientException:
>  Unable to execute HTTP request: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

We are having multiple devices on some of the devices it is happening all the time, while on others intermitently.
We are using aws-android-sdk-2.2.16.

Thanks.

**Comment by karthiksaligrama** [comment] 2016-12-13 18:28
I cant reproduce this problem. Can you give me more insight into what you are doing? Also an alternative would be to update to the latest SDK and see if that fixes your problem.

**Comment by karthiksaligrama** [comment] 2016-12-15 22:45
resolving this issue, please reopen if the problem persists

**Closed by karthiksaligrama** 2016-12-15 22:45 UTC
